### ISSUE TITLE
Remove Null from oneof's

### ISSUE THREAD

**Issue by adammitchelldev** [graknlabs/protocol#37]
## Problem to Solve

We use a oneof with a custom `Null` message to represent deliberately missing values in protobuf. This is non-standard since google provides standard Null messages, but also, oneof's in protobuf already have a "not set" state, making the Null message redundant.

## Proposed Solution

We should replace all of our usages with either single-field oneofs or normal messages (which are always optionally not set).

**Comment by alexjpwalker** [comment]
This was removed a while back.
